server:
  port: 8082
  tomcat:
    threads:
      max: 1
      min-spare: 1
    max-connections: 1
    accept-count: 1
    connection-timeout: 20000

logging:
  level:
    #jakarta.servlet.Filter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    #org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  profiles:
    include: private

custom:
  env: ${CUSTOM_ENV:dev}

jwt:
  refresh-token:
    expiry-ms: 2592000000 # 30일 (30 * 24 * 60 * 60 * 1000)



