server:
  port: 8082
  tomcat:
    threads:
      max: 1
      min-spare: 1
    max-connections: 1
    accept-count: 1
    connection-timeout: 20000

logging:
  level:
    jakarta.servlet.Filter: DEBUG
    #org.springframework.security.web.FilterChainProxy: DEBUG


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SecurityTest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 5609yang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  #  data:
  #    web:
  #      pageable:
  #        one-indexed-parameters: true
jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: none
  show-sql: true
  properties:
    hibernate:
      format_sql: true

jwt:
  secret: 84a831ea5e9c5d6ef52cf5e6ce7c0e8ff527e0f6b8f70daa564fd55b1f9a7949

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:schema.sql
#  session:
#    jdbc:
#      initialize-schema: always


#logging:
#  level:
#    org.hibernate.type.descriptor.sql: info

custom:
  env: ${CUSTOM_ENV:dev}



